"""
formatter_md.py
---------------
Generates a full-fledged API documentation Markdown file from a list of RouteInfo objects.

Output structure:
  - Cover: title, timestamp, summary stats
  - Per-app sections with per-endpoint subsections
  - Each endpoint: method badges, path params, auth, permissions,
    serializer, filters, docstring, URL name
  - Appendix: complete flat route table
"""

from __future__ import annotations

import re
from datetime import datetime
from typing import Optional
from collections import defaultdict

from drf_routes.utils.resolver import RouteInfo


# ──────────────────────────────────────────────────────────────
#  Method badge helpers (emoji + inline code, GFM-compatible)
# ──────────────────────────────────────────────────────────────

METHOD_EMOJI = {
    "GET":     "🟢",
    "POST":    "🔵",
    "PUT":     "🟡",
    "PATCH":   "🟠",
    "DELETE":  "🔴",
    "HEAD":    "⚫",
    "OPTIONS": "⚫",
}


def _method_badge(method: str) -> str:
    emoji = METHOD_EMOJI.get(method, "⚪")
    return f"{emoji} `{method}`"


def _methods_line(methods: list[str]) -> str:
    if not methods:
        return "_No methods detected_"
    return "  ".join(_method_badge(m) for m in methods)


# ──────────────────────────────────────────────────────────────
#  Small helpers
# ──────────────────────────────────────────────────────────────

def _badge_list(items: list[str], prefix: str = "") -> str:
    """Render a list of names as inline code items."""
    if not items:
        return "_none_"
    return "  ".join(f"`{prefix}{i}`" for i in items)


def _slug(text: str) -> str:
    """Convert text to a GitHub-compatible anchor slug."""
    return re.sub(r"[^a-z0-9-]", "-", text.lower()).strip("-")


def _divider() -> str:
    return "\n---\n"


# ──────────────────────────────────────────────────────────────
#  Cover section
# ──────────────────────────────────────────────────────────────

def _render_cover(routes: list[RouteInfo], project_name: str) -> str:
    total       = len(routes)
    drf_count   = sum(1 for r in routes if r.is_drf)
    plain_count = total - drf_count
    apps        = sorted({r.app_name or "—" for r in routes})
    now         = datetime.now().strftime("%Y-%m-%d %H:%M")

    method_counts: dict[str, int] = defaultdict(int)
    for r in routes:
        for m in r.http_methods:
            method_counts[m] += 1

    method_summary = "  ".join(
        f"{_method_badge(m)} ×{method_counts[m]}"
        for m in ["GET", "POST", "PUT", "PATCH", "DELETE"]
        if method_counts[m]
    )

    lines = [
        f"# 📡 {project_name} — API Reference",
        "",
        f"> Auto-generated by **drf-routes** on `{now}`  ",
        f"> {total} endpoint(s) across {len(apps)} app(s)",
        "",
        "## 📊 Summary",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Total endpoints | **{total}** |",
        f"| DRF endpoints | **{drf_count}** |",
        f"| Plain Django endpoints | **{plain_count}** |",
        f"| Apps | {', '.join(f'`{a}`' for a in apps)} |",
        "",
        "**Methods breakdown:**",
        "",
        method_summary,
    ]
    return "\n".join(lines)


# ──────────────────────────────────────────────────────────────
#  Table of Contents
# ──────────────────────────────────────────────────────────────

def _render_toc(grouped: dict[str, list[RouteInfo]]) -> str:
    lines = ["## 📑 Table of Contents", ""]
    for app, routes in grouped.items():
        app_label = app or "Other"
        anchor = _slug(app_label)
        lines.append(f"- [{app_label}](#{anchor})")
        for r in routes:
            ep_label = r.url
            ep_anchor = _slug(f"{app_label}-{r.url}")
            lines.append(f"  - [`{ep_label}`](#{ep_anchor})")
    return "\n".join(lines)


# ──────────────────────────────────────────────────────────────
#  Single endpoint section
# ──────────────────────────────────────────────────────────────

def _render_endpoint(r: RouteInfo, app_label: str) -> str:
    extra       = r.extra or {}
    path_params = extra.get("path_params", [])
    doc         = extra.get("docstring")
    permissions = extra.get("permission_classes", [])
    auth        = extra.get("authentication_classes", [])
    filters     = extra.get("filter_backends", [])
    search      = extra.get("search_fields", [])
    ordering    = extra.get("ordering_fields", [])
    filterset   = extra.get("filterset_fields", [])
    pagination  = extra.get("pagination_class")

    # Heading with an anchor that matches the TOC
    anchor_id   = _slug(f"{app_label}-{r.url}")
    lines = [
        f"### <a name=\"{anchor_id}\"></a>`{r.url}`",
        "",
    ]

    # Type badge
    type_badge  = "🔷 **DRF**" if r.is_drf else "🔹 **Django**"
    lines.append(f"{type_badge}  |  **View:** `{r.view_name}`  |  **Module:** `{r.module}`")
    lines.append("")

    # Methods
    lines.append("**Methods**")
    lines.append("")
    lines.append(_methods_line(r.http_methods))
    lines.append("")

    # Path parameters
    if path_params:
        lines.append("**Path Parameters**")
        lines.append("")
        lines.append("| Parameter | Type |")
        lines.append("|-----------|------|")
        for p in path_params:
            lines.append(f"| `{{{p}}}` | string |")
        lines.append("")

    # Metadata table
    meta_rows = []
    if r.name:
        meta_rows.append(("URL Name", f"`{r.name}`"))
    if r.serializer_class:
        meta_rows.append(("Serializer", f"`{r.serializer_class}`"))
    if pagination:
        meta_rows.append(("Pagination", f"`{pagination}`"))
    if permissions:
        meta_rows.append(("Permissions", _badge_list(permissions)))
    if auth:
        meta_rows.append(("Authentication", _badge_list(auth)))
    if filters:
        meta_rows.append(("Filter Backends", _badge_list(filters)))
    if search:
        meta_rows.append(("Search Fields", _badge_list(search)))
    if ordering:
        meta_rows.append(("Ordering Fields", _badge_list(ordering)))
    if filterset:
        meta_rows.append(("Filterset Fields", _badge_list(filterset)))

    if meta_rows:
        lines.append("**Details**")
        lines.append("")
        lines.append("| Field | Value |")
        lines.append("|-------|-------|")
        for label, value in meta_rows:
            lines.append(f"| {label} | {value} |")
        lines.append("")

    # Docstring
    if doc:
        newline_replacement = "  \n> "
        lines.append("**Description**")
        lines.append("")
        lines.append(f"> {doc.replace(chr(10), newline_replacement)}")
        lines.append("")

    return "\n".join(lines)


# ──────────────────────────────────────────────────────────────
#  Per-app section
# ──────────────────────────────────────────────────────────────

def _render_app_section(app: str, routes: list[RouteInfo]) -> str:
    app_label = app or "Other"
    anchor    = _slug(app_label)
    lines = [
        f"## <a name=\"{anchor}\"></a>🗂 {app_label}",
        "",
        f"_{len(routes)} endpoint(s)_",
        "",
    ]
    for r in routes:
        lines.append(_render_endpoint(r, app_label))
        lines.append("")
    return "\n".join(lines)


# ──────────────────────────────────────────────────────────────
#  Appendix: flat table
# ──────────────────────────────────────────────────────────────

def _render_appendix(routes: list[RouteInfo]) -> str:
    lines = [
        "## 📋 Appendix — All Routes",
        "",
        "| URL | Methods | View | Serializer | App | Name |",
        "|-----|---------|------|------------|-----|------|",
    ]
    for r in routes:
        methods    = " ".join(r.http_methods) if r.http_methods else "—"
        serializer = r.serializer_class or "—"
        app        = r.app_name or "—"
        name       = r.name or "—"
        lines.append(f"| `{r.url}` | {methods} | `{r.view_name}` | `{serializer}` | {app} | {name} |")
    return "\n".join(lines)


# ──────────────────────────────────────────────────────────────
#  Public entry point
# ──────────────────────────────────────────────────────────────

def format_markdown(routes: list[RouteInfo], project_name: str = "Django") -> str:
    """
    Generate a complete API reference Markdown document.

    Args:
        routes:       List of RouteInfo objects.
        project_name: Used in the document title (defaults to 'Django').

    Returns:
        A full Markdown string suitable for writing to a .md file.
    """
    if not routes:
        return "# API Reference\n\n_No routes found._\n"

    # Group by app, preserving insertion order, unknown app last
    grouped: dict[str, list[RouteInfo]] = defaultdict(list)
    for r in routes:
        grouped[r.app_name or ""].append(r)

    # Sort: named apps first (alphabetical), unnamed last
    sorted_groups: dict[str, list[RouteInfo]] = {}
    for key in sorted(grouped.keys(), key=lambda k: ("" if k else "\xff", k)):
        sorted_groups[key] = grouped[key]

    sections = [
        _render_cover(routes, project_name),
        _divider(),
        _render_toc(sorted_groups),
        _divider(),
    ]

    for app, app_routes in sorted_groups.items():
        sections.append(_render_app_section(app, app_routes))
        sections.append(_divider())

    sections.append(_render_appendix(routes))
    sections.append("\n\n---\n_Generated by [drf-routes](https://github.com/yourusername/drf-routes)_\n")

    return "\n".join(sections)
